# Generated by Django 5.1.7 on 2025-07-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
