# Generated by Django 5.1.7 on 2025-08-01 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, null=True, related_name='deleted_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
