# Generated by Django 5.1.7 on 2025-08-08 04:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='hided_from',
            field=models.ManyToManyField(related_name='hided_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
