# Generated by Django 5.1.7 on 2025-08-10 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_chatroom_deleted_for_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, related_name='deleted_chatrooms', through='chat.ChatRoomDelete', to=settings.AUTH_USER_MODEL),
        ),
    ]
