# Generated by Django 5.1.7 on 2025-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='agree_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
