# Generated by Django 5.1.7 on 2025-07-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patientprofile_agree_to_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='agree_to_terms',
            new_name='agree_terms',
        ),
    ]
