# Generated by Django 5.1.7 on 2025-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(related_name='helpful_reviews', to='app.patientprofile'),
        ),
        migrations.AddField(
            model_name='review',
            name='not_helpful',
            field=models.ManyToManyField(related_name='not_helpful_reviews', to='app.patientprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
