# Generated by Django 5.1.7 on 2025-07-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_helpful_review_not_helpful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='helpful_reviews', to='app.patientprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='not_helpful',
            field=models.ManyToManyField(blank=True, related_name='not_helpful_reviews', to='app.patientprofile'),
        ),
    ]
