# Generated by Django 5.1.7 on 2025-07-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_review_helpful_alter_review_not_helpful'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('rating',)},
        ),
    ]
