# Generated by Django 5.1.7 on 2025-08-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_adminprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
