# Generated by Django 5.1.7 on 2025-08-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-rating',)},
        ),
    ]
